name: PHP Code Sniffer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Mark repo as safe
      run: git config --global --add safe.directory /app

    - name: Composer Install
      uses: php-actions/composer@v6
      with:
         php_extensions: sockets pdo_pgsql

    - name: PHPCS
      run: composer run phpcs
