name: PHP Code Sniffer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: sockets, pdo_pgsql

    - name: Mark repo as safe
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Run PHP CodeSniffer
      run: composer run phpcs
